name = "pudim-site"
main = "out/index.html"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.jsx", "pages/**/*.jsx", "components/**/*.jsx", "styles/**/*.css"]

[build.upload]
format = "service-worker"

[env.production]
name = "pudim-site-production"
